// Name:		Matrikelnummer:
// Name:		Matrikelnummer:
// Datum:

	.file	"aufgabe2.S"
	.text			@ legt eine Textsection fuer PrgrammCode + Konstanten an
	.align	2		@ sorgt dafuer, dass nachfolgende Anweisungen auf einer durch 4 teilbaren Adresse liegen
				@ unteren 2 Bit sind 0
	.global	main		@ nimmt das Symbol main in die globale Sysmboltabelle auf
	.type	main,function
main:
	adr	r1, marke
	MOV	r0, #3
	MSR	CPSR, r0
	SUBEQS 	r1, r1, r1


		


	bx	lr
marke:	.word	0x12345678
	
.Lfe1:
	.size	main,.Lfe1-main

	.data
marke1:	.word 0x87654321

// End of File
